### ISSUE TITLE
HTTP client is initialised without any timeouts

### ISSUE THREAD

**Issue by Xiol** [ukfast/sdk-go#101]
### What is the issue?

The http.Client in NewAPIConnection is initialised without any timeouts set, it may cause applications using it to hang indefinitely if the API is unresponsive.

### Steps To Reproduce

N/A

### Expected behaviour

Client should be initialised with _some_ default timeout. Users of the SDK can override by instantiating their own `APIConnection`, but the defaults should prevent a client from hanging indefinitely.

### Possible fixes

https://github.com/ukfast/sdk-go/blob/master/pkg/connection/connection.go#L48

```go
func NewAPIConnection(credentials Credentials) *APIConnection {
	return &APIConnection{
		Credentials: credentials,
		HTTPClient:  &http.Client{
                        Timeout: 120 * time.Second
                },
		APIURI:      apiURI,
		APIScheme:   apiScheme,
		UserAgent:   userAgent,
	}
}
```

### Additional context

https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

**Comment by 0x4c6565** [comment]
Added https://github.com/ukfast/sdk-go/pull/112 to address
